name: CI/CD Pipeline

on:
  push:
    branches:
      - main  # Ou a branch que você deseja monitorar
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 21
        uses: actions/setup-java@v2
        with:
          java-version: '21'
          distribution: 'adopt'

      - name: Ensure Gradle Wrapper is executable
        run: chmod +x ./gradlew

      - name: Build with Gradle
        run: ./gradlew build || { echo 'Build failed'; exit 1; }

      - name: Run Tests
        run: ./gradlew test || { echo 'Tests failed'; exit 1; }

      - name: Package
        run: ./gradlew assemble || { echo 'Packaging failed'; exit 1; }

      - name: Upload Test Results
        if: failure()  # Apenas se os testes falharem
        uses: actions/upload-artifact@v2
        with:
          name: test-results
          path: build/reports/tests/test/index.html

      - name: Deploy
        run: |
          echo "Deploying application..."
          # Adicione os comandos de deploy aqui